apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    app: {{ include "etcd.name" . }}
    app.kubernetes.io/name: {{ include "etcd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP | quote }}
  selector:
    app: {{ include "etcd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  publishNotReadyAddresses: true
  ports:
    - name: etcd-client
      port: {{ .Values.service.ports.client }}
    - name: etcd-server
      port: {{ .Values.service.ports.server }}
    - name: etcd-metrics
      port: {{ .Values.service.ports.metrics }}
